# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
 #name = "Posts"
  #url = "#posts"
  #weight = 20

[[main]]
  name = "Research"
  url = "projects"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

#[[main]]
#  name = "Publication"
#  url = "publication"
#  weight = 60
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "Resume"
    url = "https://www.dropbox.com/s/8348dy5228h2zmi/Resume_Whitehead%20%5BJan%2022%5D.pdf?dl=0"
    weight = 70
 [[main]]
    name = "CV"
    url = "https://www.dropbox.com/s/bit0xd90lx1kg30/CV%20%5BJan21%5D.docx?dl=0"
    weight = 80
